### ISSUE TITLE
该更新了

### ISSUE THREAD

**Issue by zhizhou57** [CS-Tao/whu-library-seat#33]
新的图书馆系统在预约确认时增加了验证码，现有软件已经不适用

**Comment by destiny11-cloud** [comment]
附议

**Comment by zhouli159159** [comment]
确实

**Comment by CS-Tao** [comment]
我最近没时间更新，有需要可以使用 [@orangeboyChen](https://github.com/orangeboyChen) 开发的软件
> 链接: https://pan.baidu.com/s/1j2IDTDbd157GQt2GCAKEDw 提取码: mxfq

**Comment by JiaJinQin** [comment]
还是Tao哥的好用，用别的咳嗽

**Comment by little-weakduck** [comment]
orangeBoy 的可以直接过验证码（爱了爱了）

**Comment by CS-Tao** [comment]
原接口已停用，目前没有适配新接口的计划，感谢大家长期的支持
